# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# name: Build

# on:
#   push:
#     branches: [master]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: google-github-actions/setup-gcloud@master
#         with:
#           version: "290.0.1"
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true
#       - name: Setup GCloud
#         run: |
#           gcloud config set project mig-platform
#       - uses: actions/checkout@v2
#       - name: Deploy APIs
#         run: |
#           echo "$FIREBASE_KEY" > firebase.json
#           echo "$FINANCE_KEY" > key.json
#           chmod a+x ./deploy.sh
#           ./deploy.sh
#         shell: bash
#         env:
#           FIREBASE_KEY: ${{secrets.FIREBASE_KEY}}
#           FINANCE_KEY: ${{secrets.FINANCE_KEY}}
